### ISSUE TITLE
Support CockroachDB

### ISSUE THREAD

**Issue by delaneyj** [kristiandupont/kanel#158]
Tried to run on a cockroach db instance and got 

```ts
$ ./node_modules/.bin/kanel -c ./src/sql/configs/kanel.js
Kanel
Connecting to foo on localhost
 - Clearing old files in ./libs/foo/src/generated/sql
./node_modules/extract-pg-schema/node_modules/knex/lib/dialects/postgres/index.js:108
        resolver(/^PostgreSQL (.*?)( |$)/.exec(resp.rows[0].version)[1]);
                                                                    ^

TypeError: Cannot read property '1' of null
    at Query.<anonymous> (./node_modules/extract-pg-schema/node_modules/knex/lib/dialects/postgres/index.js:108:69)
    at Query.handleReadyForQuery (./node_modules/pg/lib/query.js:138:12)
    at Client._handleReadyForQuery (./node_modules/pg/lib/client.js:290:19)
    at Connection.emit (node:events:378:20)
    at ./node_modules/pg/lib/connection.js:114:12
    at Parser.parse (./node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (./node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
error Command failed with exit code 1.
```

You can run an instance with `docker run -it -p 26257:26257 -p 8080:8080 cockroachdb/cockroach start-single-node --insecure`

**Comment by kristiandupont** [comment]
Yeah sorry, Kanel is made for Postgresql only. It's rather strictly tied to the way the schemas are structured etc.
