### ISSUE TITLE
Postgres connection string not accepted

### ISSUE THREAD

**Issue by hexcowboy** [kristiandupont/kanel#291]
When using the [example command](https://kristiandupont.github.io/kanel/getting-started.html) I'm receiving an error:

```bash
$ npx kanel -d "postgresql://localhost:5432/acme" -o ./src/models
# Invalid value for option 'database' - expected type string, received value: postgresql://localhost:5432/acme.
```

When passing `connectionString` to client using the `.kanelrc.js`:

```js
require("dotenv").config();

/** @type {import('kanel').Config} */
module.exports = {
  connection: {
    connectionString: process.env.DATABASE_URL,
  },

  preDeleteModelFolder: true,
  outputPath: "./src/types",
};
```

```
Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
    at Object.continueSession (/Users/hex/repos/8aa8/webapp/node_modules/pg/lib/sasl.js:24:11)
    at Client._handleAuthSASLContinue (/Users/hex/repos/8aa8/webapp/node_modules/pg/lib/client.js:257:10)
    at Connection.emit (node:events:527:28)
    at /Users/hex/repos/8aa8/webapp/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/Users/hex/repos/8aa8/webapp/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/Users/hex/repos/8aa8/webapp/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
```

**Comment by kristiandupont** [comment]
The cli issue looks like a plain bug, I will look into that. Regarding setting the connection string in .kanelrc, try setting it directly to `connection` instead of creating an object:

```javascript
/** @type {import('kanel').Config} */
module.exports = {
  connection: process.env.DATABASE_URL,

  preDeleteModelFolder: true,
  outputPath: "./src/types",
};
```

**Comment by hexcowboy** [comment]
> Regarding setting the connection string in .kanelrc, try setting it directly to `connection` instead of creating an object

This works, thank you!
