### ISSUE TITLE
Attempting to connect to remote database still tries to connect to local database

### ISSUE THREAD

**Issue by magnusrodseth** [kristiandupont/kanel#382]
I am trying to connect to a database not running locally on my machine, but rather remotely.

I have the following `.kanelrc.js`. Note how I have only changed the connection attributes:

```js
const path = require("path");

/** @type {import('kanel').Config} */
module.exports = {
  connection: {
    host: process.env.TIMESERIES_DB_HOST,
    user: process.env.TIMESERIES_DB_USERNAME,
    password: process.env.TIMESERIES_DB_PASSWORD,
    database: process.env.TIMESERIES_DB_NAME,
    port: process.env.TIMESERIES_DB_PORT,
  },

  preDeleteModelFolder: true,
  outputPath: "./src/schemas",

  customTypeMap: {
    "pg_catalog.tsvector": "string",
    "pg_catalog.bpchar": "string",
  },
};
```

I get the following error message in my terminal:

```sh
Kanel
Using config file: /Users/.../timeseries/.kanelrc.js
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
 ERROR  Command failed with exit code 1: kanel

pnpm: Command failed with exit code 1: kanel
    at makeError (/Users/magnusrodseth/Library/pnpm/global/5/.pnpm/pnpm@7.29.1/node_modules/pnpm/dist/pnpm.cjs:23074:17)
    at handlePromise (/Users/magnusrodseth/Library/pnpm/global/5/.pnpm/pnpm@7.29.1/node_modules/pnpm/dist/pnpm.cjs:23645:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler [as dlx] (/Users/magnusrodseth/Library/pnpm/global/5/.pnpm/pnpm@7.29.1/node_modules/pnpm/dist/pnpm.cjs:219303:7)
    at async /Users/magnusrodseth/Library/pnpm/global/5/.pnpm/pnpm@7.29.1/node_modules/pnpm/dist/pnpm.cjs:227043:21
    at async main (/Users/magnusrodseth/Library/pnpm/global/5/.pnpm/pnpm@7.29.1/node_modules/pnpm/dist/pnpm.cjs:227010:34)
    at async runPnpm (/Users/magnusrodseth/Library/pnpm/global/5/.pnpm/pnpm@7.29.1/node_modules/pnpm/dist/pnpm.cjs:227242:5)
    at async /Users/magnusrodseth/Library/pnpm/global/5/.pnpm/pnpm@7.29.1/node_modules/pnpm/dist/pnpm.cjs:227234:7
```

It seems like Kanel still tries to connect to a local database. I have tried generating types using the command line (without `.kanelrc.js`):

```sh
pnpx kanel -d 'my_connection_string_here' -o ./src/models
```

I still get the same error.

**Why could this be?**

**Comment by magnusrodseth** [comment]
fixed
