### ISSUE TITLE
Remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by magnusrodseth** [kristiandupont/kanel#383]
I get the following error when connecting to the database:

```sh
Kanel
Using config file: /Users/magnusrodseth/dev/jrc/effisense/sensor-dashboard/packages/timeseries/.kanelrc.js
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 0s | 0/10error: remaining connection slots are reserved for non-replication superuser connections
    at Parser.parseErrorMessage (/Users/magnusrodseth/dev/jrc/effisense/sensor-dashboard/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:)
    at Parser.handlePacket (/Users/magnusrodseth/dev/jrc/effisense/sensor-dashboard/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:2)
    at Parser.parse (/Users/magnusrodseth/dev/jrc/effisense/sensor-dashboard/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/magnusrodseth/dev/jrc/effisense/sensor-dashboard/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 140,
  severity: 'FATAL',
  code: '53300',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postinit.c',
  line: '879',
  routine: 'InitPostgres'
}
 ELIFECYCLE  Command failed with exit code 1.
```

Notice the error `error: remaining connection slots are reserved for non-replication superuser connections`.

Is this an issue with the database or the library? If so, do you have any idea how to fix it?

**Comment by kristiandupont** [comment]
This seems to be an issue with the database, apparently there are too many connections already?

For what it's worth, I recommend running Kanel against your local development database assuming you have one and that it has the exact same schema as your production database. It's better suited for when you create migrations.

**Comment by magnusrodseth** [comment]
@kristiandupont I am not able to run this database locally, as it runs in a serverless environment. Does Kanel support a database pool, in order to not open an unnecessary amount of connections?

**Comment by kristiandupont** [comment]
Ah, I see.

Well, the connection configuration goes straight to the `pg` package. You can look into the options [here](https://node-postgres.com/features/connecting)

**Comment by magnusrodseth** [comment]
Just to state it: I fixed it by increasing the amount of `maximum_connections` from 25 to 50.

However, If the Kanel connection config goes straight to the `pg` package, how can the developer interface against the `pg` package through Kanel? I can't seem to find any settings on this in the `.kanelrc.js`. 

With that being said: When I got it to work, it really is quite a great library 🚀
