### ISSUE TITLE
For columns having multiple foreign key constraints only one is resolved

### ISSUE THREAD

**Issue by hixus** [kristiandupont/kanel#392]
We have couple cases where we want to be sure that the id exists in two other tables. As we are also using Hasura this helps with defining relations.

Let's say we have tables a, b and c. We want to allow inserting a row to table c only if a and b have related row. With Postgres it's fine to have multiple foreign key constrains. However it seems Kanel only takes the first constraint.
 
This means we get interface `interface table_c { ref_id: aId }` when it should be `interface table_c { ref_id: aId | bId }`

Otherwise wouldn't matter but as we are using the flavor approach `type aId = string & { __flavor?: 'a_id' }` and `type bId = string & { __flavor?: 'b_id' }` are not exactly same. 

Also as the ordering of fk's is arbitary with postgres creating the types from empty or existing dataset results in different id selected. With means typecheck will fail on some instances.

**Comment by kristiandupont** [comment]
Hah interesting, I haven't run into this myself yet but obviously it's a problem!
As you might have noticed, I have been a bit slow to respond to issues lately but I hope I can get around to this soon.

**Comment by kristiandupont** [comment]
So I've just pushed a fix for this. I don't have a setup for testing it. Would you be able to try it out if I publish an alpha version?

**Comment by hixus** [comment]
Sure, happy to test it.

**Comment by kristiandupont** [comment]
You should be able to now: `v3.3.0-beta.0` is published.

**Comment by hixus** [comment]
Thanks. With minimal sample seems to work fine but the actual db type creation now fails. I will debug more next week.

 This works fine:
  ```
  CREATE TABLE a (
    id TEXT PRIMARY KEY
);

CREATE TABLE b (
    id TEXT PRIMARY KEY,
    a_id TEXT REFERENCES a(id)
);

CREATE TABLE c (
    id TEXT PRIMARY KEY,
    ref_id TEXT
);

ALTER TABLE c
    ADD CONSTRAINT fk_c_a FOREIGN KEY (ref_id) REFERENCES a (id),
    ADD CONSTRAINT fk_c_b FOREIGN KEY (ref_id) REFERENCES b (id);
``` 

However actual db throws
```
    TypeError: Cannot destructure property 'name' of 'undefined' as it is undefined.
    at ImportGenerator.addImport (/Users/hixus/example/node_modules/kanel/build/ImportGenerator.js:16:17)
    at /Users/hixus/example/node_modules/kanel/build/render.js:62:82
    at Array.forEach (<anonymous>)
    at /Users/hixus/example/node_modules/kanel/build/render.js:62:42
    at Array.forEach (<anonymous>)
    at processDeclaration (/Users/hixus/example/node_modules/kanel/build/render.js:56:24)
    at /Users/hixus/example/node_modules/kanel/build/render.js:88:34
    at Array.forEach (<anonymous>)
    at render (/Users/hixus/example/node_modules/kanel/build/render.js:84:18)
    at /Users/hixus/example/node_modules/kanel/build/processDatabase.js:67:44
```

**Comment by kristiandupont** [comment]
I wasn't able to reproduce the issue you had there, but I did have some weird Yarn errors. I bumped the `pg` package and got things working, so I published a new release with that. Could you try and see if that helps?

**Comment by hixus** [comment]
Tested beta on actual db and got the same error. Added some logs and it seems that render.js  => processDeclaration fn => case 'interface' => property.typeImports has [undefined, undefined] which causes addImport to fail.

**Comment by hixus** [comment]
Continued with debugging this. I think there's issue in `resolveType` especially `referencedTypes` array. In our conflicting case `referencedTypes` array contained ["string", "string"] which resolves to undefined in referencedTypes.length ternary as string object doesn't have `name` or `typeImports` props.

**Comment by kristiandupont** [comment]
Sorry about dropping the ball on this! I am not sure why there would be duplicates there but I added your patch to the newest published version. Thank you for the help and let me know if the problem persists!
